# Generated by Django 5.2.15 on 2026-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD5vpYb8nQGAp_Yhvtb1Eg-R4kmw-_p8bNdgLLVgIiCA&s=10')),
                ('ciusine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
