# Generated by Django 5.2.15 on 2026-06-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='ciusine',
            new_name='cuisine',
        ),
    ]
